<?php

namespace AppBundle\Repository;

/**
 * PerformerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformerRepository extends \Doctrine\ORM\EntityRepository
{
}
